candidate_days: &cand_days 30
vacancy_days: &vac_days 60

languages: &langs ["Inglese", "Italiano", "Spagnolo", "Francese", "Tedesco", "Portoghese", "Cinese", "Giapponese", "Coreano", "Russo", "Arabo", "Olandese", "Svedese", "Polacco", "Turco", "Urdu", "Bangalese"]

regions: &reg ["Abruzzo", "Basilicata", "Calabria", "Campania", "Emilia-Romagna", "Friuli-Venezia Giulia", "Lazio", "Liguria", "Lombardia", "Marche",
  "Molise", "Piemonte", "Puglia", "Sardegna", "Sicilia", "Toscana", "Trentino-Alto Adige", "Umbria", "Valle d Aosta", "Veneto"
]

education_levels: &edu_levels ["Diploma scuola media", "Diploma scuola superiore", "Laurea triennale", "Laurea specialistica", "Dottorato/Master"]

desired_locations: &des_locations ["Locale", "Regionale", "Nazionale", "Internazionale"]

turno_preferenza: &turno_pref ["Mattina", "Pomeriggio", "Notte", "Fine Settimana"]

parttime_preferenza_perc: &parttime_pref [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

data_ingestion:  
  candidate:
    columns: ["candidateid", "first_name", "last_name", "description", "salary_low", "date_available", "will_relocate", "desired_location", "parttime_preferenza_perc", "turno_preferenza"]
    days_prior: *cand_days
  vacancy:
    columns: ["joborderid", "jobtitle", "citta", "regione", "salary", "data_inizio_validita",
      "part_time_percent", "skill_list", "titoli_richiesti", "DESCRIZIONE_USO_INTERNO", "TESTO_PUBBLICAZIONE", "RICHIESTE_AGGIUNTIVE", "REQUISITI"]
    days_prior: *vac_days
  italian_cities:
    string_columns : ["unique_identifier", "city_name", "province", "province_ext", "region", "zip"]
    numeric_columns: ["latitude", "longitude"]
  desired_locations: *des_locations
  parttime_preferenza_perc: *parttime_pref
  max_tokens: 200000


data_transformation:
  candidate:
    days_prior: *cand_days
    ner_columns: ["description", "chatwa"]
    ner_features : ["age", "date_of_birth", "location", "region", "country", "zip_code", "last_job", "second_last_job", "third_last_job", 
             "skills", "soft_skills", "languages", "certifications", "education"]
    emb_columns: ["skills_emb", "last_job_emb", "second_last_job_emb", "third_last_job_emb"]
    geo_columns: ["latitude", "longitude", "province_ext", "distance_km"]
  vacancy:
    ner_columns: ["description"]
    ner_features: ["country", "turno_preferenza", "parttime_preferenza_perc", "skills", "languages", "education", "certifications"]
    emb_columns: ["jobtitle_emb", "skills_emb"]
    days_prior: *cand_days
  education_levels: *edu_levels
  regions: *reg
  turno preferenza: *turno_pref
  parttime_preferenza_perc: *parttime_pref


app:
  default_inputs:
    max_ral: 0
    date_available: null
    will_relocate: false
    desired_locations: ""
    turno_preferenza: []
    parttime_preferenza_perc: 0
    role: ""
    location: ""
    max_distance: 20
    max_age: 0
    skills_mand: ""
    skills_opt: ""
    skills_soft: ""
    skills_languages_mand: []
    skills_languages_opt: []
    skills_education_mand: ""
    skills_education_opt: ""
    skills_certifications_mand: ""
    skills_certifications_opt: ""
    vacancy_id_raw: ""


automatch:
    columns:
      last_job: "Ultimo lavoro"
      second_last_job: "Secondo ultimo lavoro"
      third_last_job: "Terzo ultimo lavoro"
      skills: "Skills"
      languages: "Lingue"
      education: "Titolo di studio"
      certifications: "Certificazioni"
    languages:
      *langs
    education_levels: *edu_levels
    desired_locations: *des_locations
    turno preferenza:
      *turno_pref
    parttime_preferenza_perc: 
      *parttime_pref
